--<DS_SCRIPT>
-- DESCRIÇÃO..: Adicionando coluna para controle e selecao do ressarcimento SUS.
-- RESPONSAVEL: Elias Santana
-- DATA.......: 30/07/2020
-- APLICAÇÃO..: MVSAUDE
--</DS_SCRIPT>
--<USUARIO=DBAPS>

ALTER TABLE DBAPS.ITEM_RESSARCIMENTO_SUS_ANEXO DISABLE ALL TRIGGERS
/
ALTER TABLE DBAPS.ITEM_RESSARCIMENTO_SUS_ANEXO ADD SN_CONFIRMAR VARCHAR2(1)
/
ALTER TABLE DBAPS.ITEM_RESSARCIMENTO_SUS_ANEXO ADD TP_PROCEDIMENTO VARCHAR2(1)
/
UPDATE DBAPS.ITEM_RESSARCIMENTO_SUS_ANEXO SET SN_CONFIRMAR='S'
/
COMMIT;
/
ALTER TABLE DBAPS.ITEM_RESSARCIMENTO_SUS_ANEXO MODIFY SN_CONFIRMAR DEFAULT 'S' NOT NULL
/

ALTER TABLE DBAPS.ITEM_RESSARCIMENTO_SUS_ANEXO
  ADD CONSTRAINT cnt_ressarcimento_ck CHECK (
     SN_CONFIRMAR IN ('S','N')
  )
/
ALTER TABLE DBAPS.ITEM_RESSARCIMENTO_SUS_ANEXO
   ADD CONSTRAINT cnt_ressarcimento_tp_procedimento_ck CHECK (
       IN tp_procedimento('P','E')
 )
/
ALTER TABLE DBAPS.ITEM_RESSARCIMENTO_SUS_ANEXO ENABLE ALL TRIGGERS
/
COMMENT ON TABLE DBAPS.ITEM_RESSARCIMENTO_SUS_ANEXO.SN_CONFIRMAR IS 'Coluna para controle de Ressarcimento SUS.'
/
COMMENT ON TABLE DBAPS.ITEM_RESSARCIMENTO_SUS_ANEXO.TP_PROCEDIMENTO IS 'E-Exame  P-Procedimento'




